spring:
  application:
    name: LMS

  datasource:
    url: jdbc:mysql://localhost:3306/iae-lms?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: secret_mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #generate-ddl: true
    show-sql: true

  mail:
    host: localhost
    port: 1025

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 'your-client-id'
            client-secret: 'your-client-secret'

backend:
  menus:
    - name: "Dashboard"
      url: "/backend/dashboard"
      icon: "tachometer-alt"
    - name: "Empty"
      url: "/backend/empty"
      icon: "square"
    - name: Users
      url: /backend/users
      icon: users
    - name: "Collections"
      url: "/backend/collections"
      icon: "layer-group"

custom:
  block:
    separator: "===---block---==="

  ali:
    translation:
      accessKeyId: 'your-accessKeyId'
      secretAccessKey: 'your-secretAccessKey'
      endpoint: 'mt.cn-hangzhou.aliyuncs.com'
