spring:
  application:
    name: Proofread

  datasource:
    url: jdbc:mysql://localhost:3306/iae-proofread?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: secret_mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #generate-ddl: true
    show-sql: true

  mail:
    host: localhost
    port: 1025

backend:
  menus:
    - name: "Dashboard"
      url: "/backend/dashboard"
      icon: "tachometer-alt"
    - name: "Empty"
      url: "/backend/empty"
      icon: "square"
    - name: Users
      url: /backend/users
      icon: users
    - name: "Collections"
      url: "/backend/collections"
      icon: "layer-group"